# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Good Faith Collaboration 日本語訳
description: > # this means to ignore newlines until "baseurl:"
  Good Faith Collaboration: The Culture of Wikipedia (Joseph Reagle, 2010) 
  はウィキペディアを歴史的位置付けやコミュニティの文化の面から論じた本です。
  2011年春頃から、数名の有志がこの本の日本語訳を行っています。
  進捗状況と最新の翻訳結果が http://good-faith-collaboration-ja.github.io で公開されています。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://good-faith-collaboration-ja.github.io" # the base hostname & protocol for your site
repository: good-faith-collaboration-ja/good-faith-collaboration-ja.github.io
github_username: good-faith-collaboration-ja

# Build settings
markdown: kramdown
